version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/html:/system_monitoring/html"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
