# system_monitoring config
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: "system_monitoring"
    static_configs:
      - targets: ["nginx:9110"]

