{
 "title": "My basic system monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage{instance=\"localhost:9110\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_used_bytes{instance=\"localhost:9110\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mem_total_bytes{instance=\"localhost:9110\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mem_buffcache_bytes + mem_used_bytes",
     "legendFormat": "Usage + Buff/Cache"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_total_bytes{instance=\"localhost:9110\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "disk_used_bytes{instance=\"localhost:9110\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}